name: CustomHUD
main: pw.byakuren.hudplugin.CustomHUDPlugin
description: "Create a custom hud using the actionbar!"
author: "Brod8362"
version: "1.0"

commands:
  segments:
    description: View available segments and their placeholders.
    usage: /segments
  setformat:
    description: Set format for your HUD.
    usage: /setformat [state] [format]